version: '3'
services:

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        networks:
            - code-network

    nginx:
        image: nginx:latest
        ports:
            - "5000:80"
        volumes:
            - ./html:/var/www/html
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network

    php:
        build:
            context: .
        volumes:
            - ./html:/var/www/html
        networks:
            - code-network

    wp_cli:
        depends_on:
            - nginx
            - php
            - db
        image: wordpress:cli
        volumes:
            - ./html:/var/www/html
            - ./wp_cli/scripts:/scripts
        networks:
            - code-network
        command: /scripts/run.sh

networks:
    code-network:
        driver: bridge