version: '3'
services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        networks:
            - code-network

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./html:/var/www/html
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network

    wordpress:
        image: wordpress:php7.2-fpm
        volumes:
            - ./html:/var/www/html
        networks:
            - code-network

networks:
    code-network:
        driver: bridge